risedle/monorepo

- CONTRIBUTING.md
> chore: Add contribution guideline

- apps/README.md
Add guide to create new Risedle App
> chore: apps - Add guide on how to create new app

- .prettierignore
- .prettierrc.json
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- apps/README.md
- apps/docs/README.md
- apps/docs/package.json
- apps/docs/pages/index.tsx
- apps/docs/tsconfig.json
- apps/web/README.md
- apps/web/package.json
- apps/web/pages/index.tsx
- apps/web/tsconfig.json
- package.json
- packages/eslint-config-custom/package.json
- packages/tsconfig/README.md
- packages/tsconfig/base.json
- packages/tsconfig/nextjs.json
- packages/tsconfig/package.json
- packages/tsconfig/react-library.json
- packages/ui/Button.tsx
- packages/ui/package.json
- packages/ui/tsconfig.json
- turbo.json
> chore: Setup prettier

- apps/router-api/README.md
Add basic information about `router-api` and how to use the API
> chore(router-api): Add info & usage

- .prettierrc.json
- apps/README.md
- apps/cloudflare-workers-template/jest.config.js
- apps/cloudflare-workers-template/test/globals.d.ts
- apps/router-api/jest.config.js
- apps/router-api/package.json
- apps/router-api/src/chains.ts
- apps/router-api/src/index.ts
- apps/router-api/test/chains.spec.ts
- apps/router-api/test/globals.d.ts
- apps/router-api/test/index.spec.ts
- apps/router-api/tsconfig.json
- package-lock.json
- packages/tsconfig/cloudflare-workers.json
`GET /v1/chains` returns list of supported chains.
Fix RIS-218
> feat(router-api): Implement GET /v1/chains

- .github/workflows/monorepo.yml
- .github/workflows/risedle-chains-release.yml
- .gitignore
- .husky/commit-msg
- .husky/pre-commit
- .prettierignore
- README.md
- package-lock.json
- package.json
- packages/README.md
- packages/chains/README.md
- packages/chains/jest.config.ts
- packages/chains/package.json
- packages/chains/src/chains.spec.ts
- packages/chains/src/chains.ts
- packages/chains/src/index.ts
- packages/chains/tsconfig.json
Initialize Risedle SDK.
We publish the `@risedle/chains` first.
Fix RIS-228
Fix RIS-229
Fix RIS-230
Fix RIS-231
> feat(@risedle/chains): Initialize

- .github/workflows/risedle-chains-release.yml
- packages/chains/package.json
> fix(@risedle/chains): Fix auto release & publishing

- .github/workflows/risedle-quotes-release.yml
- package-lock.json
- packages/quotes/README.md
- packages/quotes/jest.config.ts
- packages/quotes/package.json
- packages/quotes/src/index.ts
- packages/quotes/src/quotes.spec.ts
- packages/quotes/src/quotes.ts
- packages/quotes/tsconfig.json
Initialize new Risedle SDK package `@risedle/quotes`.
Fix RIS-234
Fix RIS-235
Fix RIS-236
> feat(@risedle/quotes): initialize the package

- packages/chains/package.json
- packages/quotes/package.json
Fix RIS-237
Fix RIS-238
Fix RIS-239
Fix RIS-240
> chore(packages): Disable github auto-comment on release

- .github/workflows/risedle-api-prod.yml
- .github/workflows/risedle-api-stag.yml
- apps/api/README.md
> chore(api): setup continous deployment to staging and production

- apps/api/openapi.yml
- apps/api/package.json
- apps/api/src/server.ts
- package-lock.json
> feat(api): Add OpenAPI 3.0 Spec

- .github/workflows/storybook.yml
Copy directory `storybook-static` to root first then deploy
> fix(storybook): copy build directory first to root

- .github/workflows/risedle-ui-release.yml
Update workflow name to `@risedle/ui`
> refactor(@risedle/ui): update workflow name to @risedle/ui

- .prettierrc.json
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- apps/README.md
- apps/api/README.md
- apps/storybook/README.md
- apps/storybook/stories/Introduction.stories.mdx
Update introduction on https://storybook.risedle.exchange/
> docs(storybook): update introduction

- packages/types/package.json
- packages/types/src/chain.ts
> fix(@risedle/types): set dist directory as package root

- packages/chains/package.json
Publish `@risedle/chains` using `latest` tag by default
> feat(@risedle/chains): use latest tag by default

- .github/workflows/risedle-tokens-release.yml
> feat(@risedle/tokens): setup automatic release

- packages/types/src/token.ts
add `totalLiquidity` and `totalLiquidityUSD` field to `TokenInfo`
> feat(@risedle/types): add totalLiquidity and totalLiquidityUSD to TokenInfo

- packages/types/README.md
> feat(@risedle/types): trigger release

- apps/api/openapi.yml
- apps/api/package.json
Bump api from `1.0.0` to `1.1.0`
> chore(api): bump version

- packages/ui/README.md
> docs(@risedle/ui): update guide to create new component

- contracts/bsc/README.md
Step by step to run integration test against BSC mainnet
> docs(bsc): add guide to run test against BSC mainnet

- subgraphs/flt/abis/FLT.json
- subgraphs/flt/abis/FLTFactory.json
- subgraphs/flt/subgraph.yaml
- `forge build` the latest FLT repo
- Get the abi via the following command: `cat out/IFLT.sol/IFLT.json | jq ".abi" > FLT.json`
- add `FLT.json` and `FLTFactory.json` to `subgraphs/flt/abi`
- Generate the types via `npm run codegen`
> feat(subgraphs/flt): Add FLTFactory and FLT ABI

- package-lock.json
- subgraphs/flt/.gitignore
- subgraphs/flt/README.md
- subgraphs/flt/abis/ERC20.json
- subgraphs/flt/matchstick.yaml
- subgraphs/flt/package.json
- subgraphs/flt/schema.graphql
- subgraphs/flt/src/factory.ts
- subgraphs/flt/src/helpers.ts
- subgraphs/flt/subgraph.yaml
- subgraphs/flt/tests/.latest.json
- subgraphs/flt/tests/factory.test.ts
- subgraphs/flt/tests/hello.test.ts
Implement and test `handleNewFLT` event handler for `TokenCreated` event.
> feat(subgraphs/flt): implement & test handleNewFLT

- subgraphs/flt/abis/AccessControlledOffchainAggregator.json
- subgraphs/flt/schema.graphql
- subgraphs/flt/src/flt.ts
- subgraphs/flt/src/helpers.ts
- subgraphs/flt/src/snapshot.ts
- subgraphs/flt/subgraph.yaml
- subgraphs/flt/tests/flt.test.ts
- subgraphs/flt/tests/helpers.ts
- subgraphs/flt/tests/mocks.ts
- subgraphs/flt/tests/snapshot.test.ts
- Listen event from chainlink contract
- Upsert FLTHourData
- Upsert FLTDayData
- Upsert ETHPriceData
- test cases:
- given Factory without FLT
- given Factory with FLTs
> feat(subgraphs/flt): initialize and test handleAnswerUpdated

- apps/api/package.json
- subgraphs/flt/schema.graphql
- subgraphs/flt/src/flt.ts
- subgraphs/flt/src/helpers.ts
- subgraphs/flt/tests/flt.test.ts
- subgraphs/flt/tests/mocks.ts
Update trade volume (token units) and trade volume USD in Factory, FLT, FLTHourData and FLTDayData.
> feat(subgraphs/flt): update tradeVolume and tradeVolumeUSD

- subgraphs/flt/src/flt.ts
- subgraphs/flt/tests/flt.test.ts
Increase trade count in Factory, FLT, FLTHourData and FLTDayData.
> feat(subgraphs/flt): increase tradeTxns when swap

- subgraphs/flt/abis/RariFusePriceOracleAdapter.json
- subgraphs/flt/src/flt.ts
- subgraphs/flt/src/helpers.ts
- subgraphs/flt/subgraph.yaml
- subgraphs/flt/tests/flt.test.ts
- subgraphs/flt/tests/mocks.ts
Fee tracker data in Factory, FLT, FLTHourData and FLTDayData is increased on each swap
> feat(subgraphs/flt): tradeFeeUSD should be increased when swap

- subgraphs/flt/schema.graphql
- subgraphs/flt/src/flt.ts
- subgraphs/flt/src/helpers.ts
- subgraphs/flt/tests/flt.test.ts
- subgraphs/flt/tests/mocks.ts
> feat(subgraphs/flt): persist the Swap entity

- subgraphs/flt/src/flt.ts
- subgraphs/flt/src/helpers.ts
- subgraphs/flt/tests/flt.test.ts
> feat(subgraphs/flt): handleSwap if flt as tokenIn

- subgraphs/flt/schema.graphql
- subgraphs/flt/src/flt.ts
- subgraphs/flt/src/helpers.ts
- subgraphs/flt/tests/flt.test.ts
- subgraphs/flt/tests/mocks.ts
- subgraphs/flt/tests/snapshot.test.ts
- collateralPerShare use BigDecimal
- debtPerShare use BigDecimal
- totalCollateral use BigDecimal
- totalDebt use BigDecimal
> feat(subgraphs/flt): use BigDecimal in FLT parameters

- subgraphs/flt/networks.json
- subgraphs/flt/src/helpers.ts
- subgraphs/flt/subgraph.yaml
Remove `factory.flts = []` init
> fix(subgraphs/flt): remove factory.flts

- subgraphs/flt/src/factory.ts
- subgraphs/flt/src/snapshot.ts
- subgraphs/flt/tests/factory.test.ts
- subgraphs/flt/tests/snapshot.test.ts
Error:
```
Subgraph failed with non-deterministic error: failed to process trigger: block #19487278 (0x368f…c69a), transaction 853d3ac75a279b925326dd91252a255f97dbcbb503789713b3ad60219b7b6955: function handleTokenCreated not found, retry_delay_s: 1800, attempt: 4
```
> fix(subgraphs/flt): handleTokenCreated not found

- subgraphs/flt/schema.graphql
- subgraphs/flt/src/factory.ts
- subgraphs/flt/src/helpers.ts
- subgraphs/flt/src/snapshot.ts
- subgraphs/flt/src/swap.ts
- subgraphs/flt/tests/factory.test.ts
- subgraphs/flt/tests/helpers.ts
- subgraphs/flt/tests/mocks.ts
- subgraphs/flt/tests/snapshot.test.ts
Error:
```
Subgraph instance failed to run: Mapping aborted at generated/schema.ts, line 74, column 12, with message: unexpected null wasm backtrace: 0: 0x41d7 - <unknown>!src/snapshot/handleAnswerUpdated in handler `handleAnswerUpdated` at block #19487289 (84bc3f85a33ef8ac8ab67e79a4351b082cae5d768dde5bb74bda1d0641da0983), code: SubgraphSyncingFailure
```
> fix(subgraphs/flt): handle unintialized FLT

- apps/rebalancer/README.md
- apps/rebalancer/package.json
- apps/rebalancer/src/index.ts
- apps/rebalancer/tsconfig.json
- package-lock.json
Initialize rebalancer service for FLT
> feat(apps/rebalancer): initialize rebalancer bot

- apps/rebalancer/package.json
- apps/rebalancer/src/cron.ts
- package-lock.json
> feat(apps/rebalancer): add cron

- apps/rebalancer/package.json
- apps/rebalancer/src/config.ts
- apps/rebalancer/src/cron.ts
- package-lock.json
- report error to sentry
- publish error to discord
> feat(apps/rebalancer): add sentry

- .github/workflows/rebalancer-bsc.yml
- apps/rebalancer/Dockerfile
- apps/rebalancer/README.md
- apps/rebalancer/fly.toml
- setup auto deploy to fly.io on merge
- set release on sentry
> feat(apps/rebalancer): setup auto-deploy on merge

- apps/rebalancer/package.json
- package-lock.json
Fix this build https://github.com/risedle/monorepo/runs/7318882520?check_suite_focus=true
> fix(apps/rebalancer): set @types/node as dev dependencies

- apps/api/src/controllers/markets.ts
- apps/api/src/controllers/tokens.ts
- apps/api/src/routers/index.ts
- apps/api/src/services/market.ts
- apps/api/src/utils/validationChainId.ts
- apps/api/test/GetMarketsByChainID.spec.ts
- package-lock.json
- packages/tokens/package.json
- packages/tokens/src/index.ts
- packages/types/src/index.ts
- packages/types/src/market.ts
feat:  add flt markets api
example supported chain request : 
example not supported chain request :
> feat(api): implement /v1/chainId/markets

- .github/workflows/risedle-tokens-release.yml
Fix this build https://github.com/risedle/monorepo/runs/7335666401?check_suite_focus=true
> fix(@risedle/tokens): update GH_TOKEN

- apps/api/openapi.yml
- apps/api/package.json
- package-lock.json
Add `GetFuseLeveragedTokensByChainId` to OpenAPI spec
> feat(apps/api): add GetFuseLeveragedTokensByChainId openapi spec

- apps/api/package.json
- apps/api/src/services/flts.ts
- apps/api/src/services/specs/getFuseLeveragedTokensByChainId.spec.ts
- apps/api/src/services/specs/getGraphEndpointByChainId.spec.ts
- apps/api/src/services/specs/getTokenInfoFromPancakeSwapSubgraph.spec.ts
- package-lock.json
- Upgrade `@risedle/types`
- Re-organize the spec files
> chore(apps/api): upgrade @risedle/types

- apps/api/jest.config.ts
- apps/api/openapi.yml
- apps/api/src/controllers/flts.ts
- apps/api/src/routers/index.ts
- apps/api/src/services/flts.ts
- apps/api/src/services/specs/getFuseLeveragedTokenBySymbol.spec.ts
- apps/api/src/services/specs/getFuseLeveragedTokensByChainId.spec.ts
- apps/api/test/GetFuseLeveragedTokenBySymbol.spec.ts
- apps/api/test/GetFuseLeveragedTokensByChainId.spec.ts
- Update openapi spec
- Implement and test GetFuseLeveragedTokenBySymbol
> feat(apps/api): implement & test GetFuseLeveragedTokenBySymbol

- apps/api/openapi.yml
- apps/api/src/controllers/flts.ts
- apps/api/src/routers/index.ts
- apps/api/src/services/flts.ts
- apps/api/src/services/specs/getFuseLeveragedTokenPricesBySymbol.spec.ts
- apps/api/test/GetFuseLeveragedTokenPricesBySymbol.spec.ts
Implement and test GetFuseLeveragedTokenPricesBySymbol
> feat(apps/api): implement and test GetFuseLeveragedTokenPricesBySymbol

- apps/api/openapi.yml
- apps/api/src/controllers/flts.ts
- apps/api/src/routers/index.ts
- apps/api/src/services/flts.ts
- apps/api/src/services/specs/getFuseLeveragedTokenSwapsBySymbol.spec.ts
- apps/api/test/GetFuseLeveragedTokenSwapsBySymbol.spec.ts
- Update OpenAPI spec
- implement and test GetFuseLeveragedTokenSwapsBySymbol
> feat(apps/api): implement and test GetFuseLeveragedTokenSwapsBySymbol

- apps/api/openapi.yml
- apps/api/src/controllers/flts.ts
- apps/api/src/routers/index.ts
- apps/api/src/services/flts.ts
- apps/api/src/services/specs/getFuseLeveragedTokenBackingsBySymbol.spec.ts
- apps/api/test/GetFuseLeveragedTokenBackingsBySymbol.spec.ts
- subgraphs/flt/README.md
- create query
- update open api spec
- test and implement GetFuseLeveragedTokenBackingsBySymbol
> feat(apps/api): implement and test GetFuseLeveragedTokenBackingsBySymbol

- apps/interface/styles/Home.module.css
- package.json
Add `.css` file format on prettier `write` & `check` + `lint-staged`
Fix RIS-452
> feat(monorepo): check and format css files

- apps/interface/README.md
- apps/interface/components/WarningBar/index.tsx
- apps/interface/next.config.js
- apps/interface/package.json
- apps/interface/pages/_app.tsx
- apps/interface/pages/_document.tsx
- apps/interface/pages/index.tsx
- apps/interface/tests/pages/home/WarningBar.spec.tsx
- apps/interface/utils/theme.ts
- package-lock.json
https://chakra-ui.com/docs/styled-system/color-mode#color-mode-flash-issue
> chore(apps/interface): add note about dark mode

- apps/interface/components/ConnectWalletButton/index.tsx
- apps/interface/components/NavigationBar/chain.tsx
- apps/interface/components/NavigationBar/index.tsx
- apps/interface/components/NavigationBar/logo.tsx
- apps/interface/tests/pages/home/NavigationBarChainSwitcher.spec.tsx
- apps/interface/tests/pages/home/NavigationBarLogo.spec.tsx
- apps/interface/tests/pages/home/WarningBar.spec.tsx
- Remove tests that use mediaQuery
- reimplement responsive styling via css to fix load glitch
> feat(apps/interface): use css for responsive styling

- apps/interface/components/WarningBar/index.tsx
WarningBar is broken in safari due to min widht is not set
> fix(apps/interface): bug WarningBar on safari

- apps/api/src/server.ts
- Whitelist preview app on vercel
- Whitelist bsc.risedle.com
> chore(apps/api): update cors origin list

- apps/interface/README.md
Add docs about our data fetching strategy
> feat(apps/interface): add data fething strategy

- apps/interface/components/HomeHeading/index.tsx
- apps/interface/components/NavigationBar/chain.tsx
- apps/interface/pages/index.tsx
- apps/interface/tests/components/NavigationBar.spec.tsx
- apps/interface/tests/pages/home/NavigationBarChainSwitcher.spec.tsx
- apps/interface/tests/pages/home/NavigationBarLinks.spec.tsx
- apps/interface/tests/pages/home/NavigationBarLogo.spec.tsx
- apps/interface/tests/pages/home/WarningBar.spec.tsx
- apps/interface/tests/pages/home/isg.spec.ts
- apps/interface/tests/utils/getFuseLeveragedTokensSymmary.test.ts
- apps/interface/utils/fetchFuseLeveragedTokens.ts
- apps/interface/utils/formatUSD.ts
- apps/interface/utils/getBaseConfig.ts
- apps/interface/utils/getFuseLeveragedTokensSummary.ts
Implement static site generation on homepage
- Fix RIS-504
- Fix RIS-505
- Fix RIS-506
- Fix RIS-507
> feat(app/interface): implement incremental static regeneration

- apps/interface/pages/404.tsx
- apps/interface/tests/pages/404/index.spec.tsx
- apps/interface/utils/theme.ts
> feat(apps/interface): implement 404 Page

- apps/interface/components/TokenCard/chart.tsx
- apps/interface/components/TokenCard/index.tsx
- apps/interface/tests/components/TokenCardChart.spec.tsx
- apps/interface/tests/components/TokenCardChartTooltip.spec.tsx
- apps/interface/tests/components/TokenCards.spec.tsx
- apps/interface/tests/utils/recharts.mock.tsx
- apps/interface/utils/formatTimestamp.ts
- package-lock.json
Try render all charts in server
> chore(apps/interface): update TokenCardChartTooltip

- apps/interface/components/TokenCard/charts.tsx
Update css on hover and active state
> chore(apps/interface): update timeframes toggler styling

- apps/interface/components/PriceDownIcon/index.tsx
- apps/interface/components/PriceUpIcon/index.tsx
- apps/interface/components/TokenCard/index.tsx
- apps/interface/components/TokenCard/info.tsx
- apps/interface/tests/components/TokenCardInfo.spec.tsx
- apps/interface/themes/colors.ts
test and implement TokenCardInfo
> feat(apps/interface): test and implement TokenCardInfo

- apps/interface/components/InfoTooltip/index.tsx
- apps/interface/components/PriceChart/Line.tsx
- apps/interface/components/PriceChart/Tooltip.tsx
- apps/interface/components/PriceChart/index.tsx
- apps/interface/components/SwapCard/LatestPriceInfo.tsx
- apps/interface/components/SwapCard/LatestPriceInfoContainer.tsx
- apps/interface/components/SwapCard/Title.tsx
- apps/interface/components/SwapCard/index.tsx
- apps/interface/components/TokenCard/index.tsx
- apps/interface/tests/components/PriceChartLine.spec.tsx
- apps/interface/tests/components/PriceChartLineTooltip.spec.tsx
- apps/interface/tests/pages/trade/NavigationBarChainSwitcher.spec.tsx
- apps/interface/tests/pages/trade/NavigationBarLinks.spec.tsx
- apps/interface/tests/pages/trade/NavigationBarLogo.spec.tsx
- apps/interface/tests/pages/trade/WarningBar.spec.tsx
- apps/interface/utils/fetchFuseLeveragedTokenBySymbol.ts
Test and implement SwapCard PriceChart
> feat(apps/interface): test & implement SwapCard PriceChart

- apps/api/openapi.yml
- apps/api/src/controllers/flts.ts
- apps/api/src/routers/index.ts
- apps/api/src/services/flts.ts
- apps/api/src/services/specs/getUserPositionById.spec.ts
- apps/api/test/GetFuseLeveragedTokenUserPositionById.spec.ts
test and implement GetFuseLeveragedTokenUserPosition
> feat(apps/api): test and implement GetFuseLeveragedTokenUserPosition

- .github/workflows/risedle-types-release.yml
- apps/api/package.json
- apps/api/src/controllers/flt/GetFuseLeveragedTokenUserPositionById.ts
- apps/api/src/controllers/flt/index.ts
- apps/api/src/controllers/flts.ts
- apps/api/src/routers/index.ts
- apps/api/src/services/flt/GetFuseLeveragedTokenUserPositionById.ts
- apps/api/src/services/flt/index.ts
- apps/api/src/services/flts.ts
- apps/api/tests/integrations/GetFuseLeveragedTokenUserPositionById.spec.ts
- apps/api/tests/services/GetFuseLeveragedTokenBySymbol.spec.ts
- apps/api/tests/services/GetFuseLeveragedTokenUserPositionById.spec.ts
- packages/types/src/flt.ts
add FuseLeveragedTokenUserPosition
> feat(@risedle/types): add FuseLeveragedTokenUserPosition

- apps/interface/components/PriceChart/index.tsx
Hide chart on mobile and show chart on tablet, laptop, and desktop
> chore(apps/interface): hide price chart on mobile

- apps/interface/components/NavigationBarBottom/links.tsx
1. Set margin to 0
2. update `data-testid` to `NavigationBarBottomLinksPopupBackground`
> chore(apps/interface): set NavigationBarBottomLinksPopupBackground margin to 0

- apps/interface/components/ConnectWalletButton/index.tsx
- apps/interface/components/Icons/BlueIndicator.tsx
1. Fix the svg props
2. Move it to `components/Icons/BlueIndicator`
> fix(apps/interface): blue indicator icon svg name

- apps/interface/components/ConnectWalletButton/index.tsx
- apps/interface/components/Icons/BlueIndicator.tsx
- apps/interface/components/Icons/RedIndicator.tsx
1. Fix the svg props
2. Move it to `components/Icons/RedIndicator`
> fix(apps/interface): red indicator icon svg name

- .github/workflows/risedle-interface-stats.yml
- .github/workflows/risedle-ui-bundle-analyisis.yml
- package.json
add budle check size worfklow using this https://github.com/hashicorp/nextjs-bundle-analysis
> feat(apps/interface): add bundle check size

- apps/interface/components/NavigationBar/links.tsx
- apps/interface/tests/components/NavigationBar.spec.tsx
- apps/interface/tests/pages/home/NavigationBarLinks.spec.tsx
- apps/interface/tests/pages/trade/NavigationBarLinks.spec.tsx
Change href for `earn` in navigation bar to https://app.midascapital.xyz/56/pool/6
> feat(apps/interface): set "Earn" href to open new tab to midas pool (temporary)

- .github/workflows/risedle-interface-stats.yml
- apps/interface/package.json
- package.json
> fix(apps/interface): fix workflow failed to start

- .github/workflows/risedle-subgraphs-flt.yml
- subgraphs/flt/README.md
- subgraphs/flt/schema.graphql
- subgraphs/flt/src/helpers.ts
- subgraphs/flt/src/swap.ts
- subgraphs/flt/subgraph.yaml
- subgraphs/flt/tests/.latest.json
- subgraphs/flt/tests/factory.test.ts
- subgraphs/flt/tests/helpers.ts
- subgraphs/flt/tests/mocks.ts
- subgraphs/flt/tests/params.test.ts
- subgraphs/flt/tests/swap.test.ts
> feat(subgraphs/flt): add FLT params

- .github/workflows/risedle-interface-stats.yml
- apps/interface/package.json
- apps/interface/pages/_app.tsx
- package-lock.json
add progress bar when changing page
> feat(apps/interface): add progressbar

- apps/interface/themes/colors.ts
- apps/interface/themes/components/Button.ts
fixing all hover button styles. 
but let's wait  for @ayikfour confirmation about rainbow button behavior 
https://www.loom.com/share/ff9692a5588645e1b597fccc3891e5c5
> feat(apps/interface): hover button style

- apps/api/README.md
- apps/api/openapi.yml
- apps/api/package.json
- apps/api/src/services/flt/GetFuseLeveragedTokenBySymbol.ts
- apps/api/src/services/flts.ts
- apps/api/tests/integrations/GetFuseLeveragedTokenBySymbol.spec.ts
- apps/api/tests/services/GetFuseLeveragedTokenBySymbol.spec.ts
- package-lock.json
- Upgrade `@risedle/types`
- Add `change` and `changePercent`
> feat(apps/api): add collateral.change and debt.change

- apps/interface/components/PriceChart/index.tsx
- apps/interface/components/TradeInfoCard/index.tsx
> chore(apps/interface): set timerame to align left on large screen

- apps/interface/components/SwapCard/BuyAmountContainer.tsx
- apps/interface/components/SwapCard/Input.tsx
- apps/interface/components/SwapCard/index.tsx
- apps/interface/hooks/useBuyAmountStore.tsx
- apps/interface/package.json
- apps/interface/tests/utils/isValidInputAmount.spec.ts
- apps/interface/tests/utils/replacer.spec.ts
- apps/interface/utils/isValidInputAmount.ts
- apps/interface/utils/replacer.ts
- package-lock.json
- Add new dependency: `zustand`
> feat(apps/interface): test & implement BuyAmountContainer

- apps/interface/tests/components/RedIndicator.spec.tsx
add unit test for RedIndicator
Fix RIS-586
> feat(apps/interface): add unit test for RedIndicator

- apps/interface/tests/components/BlueIndicator.spec.tsx
> feat(interface/apps): add blue indicator test

- apps/interface/components/SwapHistoryCard/Table.tsx
> fix(interface/apps): remove padding

- apps/interface/components/BackingCard/History.tsx
Change `allowMultiple` to `allowToggle`
> chore(apps/interface): set allowToggle Instead of allowMultiple

- apps/api/src/services/flts.ts
- packages/types/src/flt.ts
> feat(@risedle/types): add FuseLeveragedTokenSwap

- apps/interface/components/PriceChart/Line.tsx
- apps/interface/components/PriceChart/Tooltip.tsx
- apps/interface/tests/components/PriceChartLineTooltip.spec.tsx
- apps/interface/utils/getDateFromTimestamp.ts
- apps/interface/utils/getHourFromTimestamp.ts
1. Update tooltip styling
2. Show dynamic price & changes on tooltip when hover in chart
> chore(apps/interface): update PriceChart Tooltip

- packages/types/package.json
- packages/types/src/flt.ts
add new types for swap history
> feat(@risedle/types): add new type for swap history

- apps/interface/components/ChainSwitcher/index.tsx
Whoops sorry I commited with wrong message .-.
> chore(apps/interface): refactor ChainSwitcher

- apps/api/tests/integrations/GetFuseLeveragedTokenBySymbol.spec.ts
- apps/api/tests/services/GetFuseLeveragedTokenBySymbol.spec.ts
- apps/interface/tests/utils/getFuseLeveragedTokensSummary.spec.ts
- apps/interface/utils/getFuseLeveragedTokensSummary.ts
> fix(apps/interface): use total volume instead of daily volume

- apps/interface/components/NavigationBar/logo.tsx
Change logo href from `https://risedle.com` to `baseURL` (https://bsc.risedle.com)
> chore(apps/interface): change risedle logo href in bsc

- packages/types/src/flt.ts
FuseLeverageSwapsHistory -> FuseLeveragedTokenSwaps
> fix(@risedle/types): typo FuseLeveragedTokenSwaps

- apps/interface/components/ChainSwitcher/index.tsx
Change chain icon color in chain switcher
> chore(apps/interface): update ChainIcon color

- apps/interface/tests/utils/getBaseConfig.spec.ts
- apps/interface/utils/getBaseConfig.ts
Update `BNB Smart Chain` to `BSC`
> chore(apps/interface): update BNB Smart Chain name

- apps/interface/components/NavigationBar/logo.tsx
- Wrap `Link` from ChakraUI with `NextLink`
- Change href to `/`
> fix(apps/interface): remove flash when logo clicked

- apps/interface/components/FooterBar/index.tsx
Update footer styling & test id
> chore(apps/interface): Update Footer

- apps/interface/components/PriceChart/Tooltip.tsx
Update background color and text color in light mode
> chore(apps/interface): update price tooltip style on light mode

- apps/interface/components/ChainSwitcher/index.tsx
1. Remove filter
2. Add `Blue Indicator` to current selected chain
3. Update `ChainIcon` color to follow the accent of current chain
> fix(apps/interface): remove filter on ChainSwitcher

- apps/interface/components/BackingCard/AllocationTable.tsx
- apps/interface/components/SwapCard/index.tsx
- apps/interface/components/SwapHistoryCard/Table.tsx
- apps/interface/components/SwapHistoryCard/index.tsx
fix color on trade pages
refrence : https://www.figma.com/file/7Pzq1Gxxud84944o9kO2HM/Website-1.1?node-id=5%3A10525
> fix(apps/interface): fix color on trade pages

- apps/interface/components/FuseLeveragedTokenInfoCard/Stats.tsx
- apps/interface/components/FuseLeveragedTokenInfoCard/StatsContainer.tsx
- apps/interface/components/FuseLeveragedTokenInfoCard/index.tsx
Remove BscScan link & replace max capacity with it
> chore(apps/interface): remove bscscan link

- apps/interface/components/FuseLeveragedTokenInfoCard/Description.tsx
- apps/interface/components/FuseLeveragedTokenInfoCard/index.tsx
- apps/interface/tests/components/FuseLeveragedTokenInfoCardDescription.spec.tsx
1. Add `Show more` link button in information card
2. Add testing coverage for `FuseLeveragedTokenInfoCardDescription` component
> feat(apps/interface): add "Show More" in information card

- apps/api/openapi.yml
Update `openapi.yml` to have insight generator endpoint
> chore(apps/api): update openapi.yml

- .github/workflows/risedle-quotes-release.yml
- Add `.github/workflows/risedle-quotes-release.yml` to `paths`
- Upgrade node to 18.7.0
- Cache `node_modules`
- Remove prepare and postinstall script
> chore(@risedle/quotes): update workflow

- .github/workflows/monorepo.yml
- upgrade node to 18.7.0
- Cache `node_modules`
> chore(monorepo): speedup github workflows

- apps/graph-node/Dockerfile
- apps/graph-node/README.md
- apps/graph-node/fly.toml
- apps/graph-node/run-node
- apps/ipfs/Dockerfile
- apps/ipfs/fly.toml
- apps/ipfs/ipfs-config.sh
- Deploy `graph-node` to Risedle's private network
> feat(apps/graph-node): setup graph-node deployment

- apps/api/openapi.yml
- apps/api/src/controllers/flt/GetFuseLeveragedTokensGains.ts
- apps/api/src/controllers/flt/index.ts
- apps/api/src/controllers/flts.ts
- apps/api/src/routers/index.ts
- apps/api/src/services/flt/GetFuseLeveragedTokensGains.ts
- apps/api/src/services/flt/index.ts
- apps/api/tests/services/GetFuseLeveragedTokensGains.spec.ts
1. Rename endpoint path from `/v1/{chainId}/flts/gains` to `/v1/{chainId}/flts/insight/gain` => because the first one have conflict with `/v1/{chainId}/flts/{symbol}`
2. Create router and controller for gains data
3. Use dummy service function to generate data
> feat(apps/api): create new router & controller for FLTs gain data

- apps/graph-node/Dockerfile
- apps/graph-node/fly.toml
- apps/graph-node/nginx/admin
- apps/graph-node/nginx/default
- apps/graph-node/nginx/graphiql
- apps/graph-node/nginx/index_node
- apps/graph-node/nginx/metrics
- apps/graph-node/run-node
- remove `socat` and use `nginx` as proxy
> chore(apps/graph-node): use nginx as proxy

- package-lock.json
- subgraphs/dex/README.md
- subgraphs/dex/package.json
Add step by step to deploy the subgraph
> chore(subgraphs/dex): add deployment docs

- subgraphs/dex/protocols/uniswap-v3/configs/arbitrum-one.json
- subgraphs/dex/templates/subgraph.yaml.template
Add `start_block` in `subgraph.yaml.template`
> chore(subgraphs/dex): add start_block

- apps/graph-node/fly.toml
Set `GRAPH_ETHEREUM_CLEANUP_BLOCKS` to true to reduce block storage
> chore(apps/graph-node): reduce block storage

- subgraphs/dex/protocols/uniswap-v3/handlers/handlePoolCreated.ts
- subgraphs/dex/shared/entities/getOrCreateFees.ts
- subgraphs/dex/shared/entities/getOrCreateLiquidityPool.ts
- subgraphs/dex/shared/entities/getOrCreateProtocol.ts
- subgraphs/dex/shared/entities/getOrCreateToken.ts
- subgraphs/dex/shared/entities/getOrCreateTokenLiquidityPool.ts
move `shared/getOrCreate*` to `shared/entities`
> chore(subgraphs/dex): refactor shared entities

- subgraphs/dex/protocols/uniswap-v3/handlers/handlePoolCreated.ts
- subgraphs/dex/schema.graphql
- subgraphs/dex/shared/entities/getOrCreateToken.ts
- subgraphs/dex/tests/uniswap-v3/handlePoolCreated.test.ts
We will do the aggregation via SQL instead of the graph entity field
> chore(subgraphs/dex): convert Token entity to immutable

- .github/workflows/risedle-subgraphs-dex.yml
- package.json
- subgraphs/dex/package.json
- subgraphs/dex/shared/entities/createLiquidityPool.ts
- subgraphs/dex/shared/entities/getOrCreateLiquidityPool.ts
- subgraphs/dex/shared/entities/getOrCreateProtocol.ts
- subgraphs/dex/shared/entities/getOrCreateToken.ts
- subgraphs/dex/shared/entities/getOrCreateTokenLiquidityPool.ts
- subgraphs/dex/shared/entities/getOrCreateTransaction.ts
- subgraphs/dex/shared/price/getNativeTokenPriceUSD.ts
- subgraphs/dex/shared/token/index.ts
- subgraphs/dex/tests/mocks/USDCWETH_POOL.ts
- subgraphs/dex/tests/mocks/WETH.ts
- subgraphs/dex/tests/shared/entities/createLiquidityPool.test.ts
- subgraphs/dex/tests/shared/entities/getOrCreateProtocol.test.ts
- subgraphs/dex/tests/shared/token.test.ts
- subgraphs/dex/tests/uniswap-v3/handlePoolCreated.test.ts
- subgraphs/dex/tests/uniswap-v3/utils/createPoolCreatedEvent.ts
> chore(subgraphs/dex): setup codebase linting

- subgraphs/dex/package.json
- subgraphs/dex/protocols/uniswap-v3/configs/arbitrum-one.json
- subgraphs/dex/templates/protocol.ts.template
- subgraphs/dex/templates/uniswap-v3.yaml.template
Update yaml & constant generator
> chore(subgraphs/dex): update yaml & constant generator

- packages/types/src/flt.ts
add type FuseLeveragedTokenInsight
> feat(@risedle/types): add type FuseLeveragedTokenInsight

- .github/workflows/risedle-api-stag.yml
- Upgrade node.js to v18.7.0
- Setup `node_modules` cache
> chore(apps/api): update api-stag github workflows

- subgraphs/dex/protocols/uniswap-v3/configs/arbitrum-one.json
- subgraphs/dex/protocols/uniswap-v3/handlers/handlePoolCreated.ts
- subgraphs/dex/shared/pools/index.ts
- subgraphs/dex/shared/pools/isPoolSkipped.ts
- subgraphs/dex/templates/protocol.ts.template
- subgraphs/dex/tests/shared/pools/isPoolSkipped.test.ts
- implement `isPoolSkipped(whitelisted, tokens)`
- Return true if none of tokens are in whitelist
- Otherwise return false
> feat(subgraphs/dex): add pool filtering

- .github/workflows/risedle-ui-release.yml
- add secret here https://github.com/risedle/monorepo/blob/2aa362846eb083ce9bb99c314a30833bd61286fe/.github/workflows/risedle-ui-release.yml#L17
- Example https://github.com/risedle/monorepo/blob/2aa362846eb083ce9bb99c314a30833bd61286fe/.github/workflows/risedle-types-release.yml#L19
- Upgrade node.js to 18.7.0 https://github.com/risedle/monorepo/blob/2aa362846eb083ce9bb99c314a30833bd61286fe/.github/workflows/risedle-ui-release.yml#L21
- Remove prepare and postinstall script https://github.com/risedle/monorepo/blob/2aa362846eb083ce9bb99c314a30833bd61286fe/.github/workflows/risedle-types-release.yml#L25-L28
- Add github action summary
> chore(@risedle/ui): update auto-publish workflow

- .changeset/funny-rivers-unite.md
- packages/*
Publish patch version of all packages. 
Fix RIS-784
> chore(packages): publish patch with new docs

- .github/workflows/changesets.yml
n/a
add manual trigger to changesets ci
Fix RIS-785
> fix(changesets): include all files inside .changeset directory

- .github/workflows/apps-assets-prod.yml
- apps/assets
Disable github action summary
Fix RIS-792
> chore(apps/assets): disable github action summary

- .github/workflows/changesets.yml
- packages/*
We need to force push 
> fix(changesets): force push

- .changeset/tasty-numbers-wash.md
> chore(changeset): test changeset

- .github/workflows/changesets.yml
- packages/*
We need to checkout with personal access token enabled (PAT).
> fix(changesets): checkout with access token

- .github/workflows/changesets.yml
- changeset
We need to bailout `exit 1` if there is no changeset.
> fix(changesets): bailout if there is no changeset

- .github/workflows/apps-interface-prod.yml
- .github/workflows/apps-interface-stats.yml
- apps/interface/Dockerfile
When we try to deploy the `apps/interface` it fails to build the Docker image
with the following error message:
```shell
------
> [7/8] RUN pnpm install --prod:
#10 29.51 Peer dependencies that should be installed:
#10 29.51   @babel/core@">=7.4.0 <8.0.0"
#10 29.51   @chakra-ui/styled-system@>=2.0.0
#10 29.51   @typescript-eslint/parser@^5.0.0
#10 29.51   prop-types@^15.6.0
#10 29.51   react-native@"*"
#10 29.51 
#10 29.51 hint: If you want peer dependencies to be automatically installed, add "auto-install-peers=true" to an .npmrc file at the root of your project.
#10 29.51 hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to an .npmrc file at the root of your project.
#10 29.51 
------
```
We …
> fix(apps/interface): set strict-peer-dependencies=false

- .github/workflows/apps-interface-stats.yml
`apps-interface-stats` workflow should found the bundle analysis file.
> fix(apps/interface): update stats path

- .github/workflows/apps-api-prod.yml
- .github/workflows/apps-api-stag.yml
- .github/workflows/apps-assets-prod.yml
- .github/workflows/apps-interface-prod.yml
- .github/workflows/apps-interface.yml
- .github/workflows/packages-chains.yml
- .github/workflows/packages-eslint-config.yml
- .github/workflows/packages-quotes.yml
- .github/workflows/packages-tokens.yml
- .github/workflows/packages-tsconfig.yml
- .github/workflows/packages-types.yml
- .github/workflows/packages-ui.yml
- codecov.yml
- packages/chains/package.json
- packages/chains/src/binance.ts
- packages/chains/src/index.ts
- packages/tokens/package.json
- pnpm-lock.yaml
- monorepo
We need to turn on Carryforward flags for codecov
> feat(monorepo): use carryforward flags

- .gitignore
- coverage/build.js
- package.json
- pnpm-lock.yaml
- turbo.json
Upload Istanbul generated page to vercel.
I know its crazy, but its better than codecov. ngl
> feat(monorepo): upload coverage to vercel

- README.md
- monorepo
We need to list deployed apps in the README
> chore(monorepo): add list of deployed apps

- .changeset/sweet-experts-hug.md
- packages/tsconfig
Bump version
> chore(@risedle/tsconfig): bump version

- apps/interface/tests/pages/trade/isg.spec.ts
We need to improve the test coverage for `pages/trade/[symbol].tsx]`
You can view the current coverage [here][1].
Spec file is available [here][2].
[1]: https://coverage.risedle.com/apps/interface/coverage/lcov-report/pages/trade/[symbol].tsx.html 
[2]: https://github.com/risedle/monorepo/blob/main/apps/interface/tests/pages/trade/isg.spec.ts
> chore(apps/interface): improve TradePage code coverage

- apps/interface/components/DarkmodeToggle/index.tsx
- apps/interface/components/NavigationBar/index.tsx
- apps/interface/tests/components/DarkmodeToggle.spec.tsx
We need to refactor the `DarkmodeToggle` button component
> chore(apps/interface): refactor DarkmodeToggle

- apps/interface/components/HomeHeading/index.tsx
We need to refactor the `HomeHeading` component.
> chore(apps/interface): refactor HomeHeading

- apps/interface/components/FooterBar/Sticky.tsx
We need to refactor the `StickyFooterBar` component.
The rendered element should have the following markup:
```html
<footer>
<nav>
<ul>
<li><a>link</a></li>
<li><a>link</a></li>
<li><a>link</a></li>
<li><a>link</a></li>
</ul>
</nav>
<p>copyright</p>
</footer>
```
> chore(apps/interface): refactor StickyFooterBar

- apps/interface/components/ConnectWalletButton/index.tsx
- apps/interface/components/NavigationBar/index.tsx
- apps/interface/components/NavigationBarBottom/index.tsx
We need to refactor the `ConnectWallet` button component
> chore(apps/interface): refactor ConnectWallet

- apps/interface/components/Icons/Chain.tsx
We need to refactor the `ChainIcon` component.
Use default imports for all utils and sub-components
> chore(apps/interface): refactor ChainIcon

- apps/interface/components/SwapCard/MaxButton.tsx
We need to refactor `SwapCardMaxButton` component.
> chore(apps/interface): refactor SwapCardMaxButton

- apps/interface/components/SwapCard/SellAmountContainer.tsx
We need to refactor `SwapCardSellAmountContainer` component.
> chore(apps/interface): refactor SwapCardSellAmountContainer

- apps/interface/components/SwapCard/SlippageToleranceRadioGroup.tsx
We need to refactor `SlippageToleranceRadioGroup` component.
> chore(apps/interface): refactor SlippageToleranceRadioGroup

- apps/interface/components/SwapCard/BuyQuoteContainer.tsx
We need to refactor `SwapCardBuyQuoteContainer` component.
> chore(apps/interface): refactor SwapCardBuyQuoteContainer

- apps/interface/components/SwapCard/BuyAmountContainer.tsx
We need to refactor `SwapCardBuyAmountContainer` component.
> chore(apps/interface): refactor SwapCardBuyAmountContainer

- apps/interface/components/SwapCard/Balance.tsx
We need to refactor `SwapCardBalance` component.
> chore(apps/interface): refactor SwapCardBalance

- apps/interface/components/SwapCard/BuyBalanceContainer.tsx
We need to refactor `SwapCardBuyBalanceContainer` component.
> chore(apps/interface): refactor SwapCardBuyBalanceContainer

- apps/interface/components/SwapCard/Quote.tsx
We need to refactor `SwapCardQuote` component.
> chore(apps/interface): refactor SwapCardQuote

- apps/interface/components/SwapCard/Input.tsx
We need to refactor `SwapCardInput` component.
> chore(apps/interface): refactor SwapCardInput

- apps/interface/components/NavigationBar/index.tsx
- apps/interface/components/NavigationBar/links.tsx
- apps/interface/components/NavigationBar/logo.tsx
- apps/interface/pages/shareable.tsx
- apps/interface/tests/components/NavigationBar.spec.tsx
We need to refactor the `NavigationBar` component.
First we need to use default import for all subcomponents:
```typescript
// this
import { NavigationBarLogo } from "./logo";
import { NavigationBarLinks } from "./links";
// to this
import NavigationBarLogo from "./logo";
import NavigationBarLinks from "./links";
```
Then we need to use one defaule export fot the component.
We need to remove `export` in this line:
```typescript
export const NavigationBar ...
```
We may also need to refactor all sub components to use default export.
> chore(apps/interface): refactor NavigationBar

- apps/interface/components/PriceChart/Line.tsx
- apps/interface/components/PriceChart/Tooltip.tsx
- apps/interface/components/PriceChart/index.tsx
- apps/interface/tests/components/NavigationBar.spec.tsx
- apps/interface/tests/components/PriceChartLine.spec.tsx
- apps/interface/tests/components/PriceChartLineTooltip.spec.tsx
- apps/interface/utils/getDateFromTimestamp.ts
- apps/interface/utils/getHourFromTimestamp.ts
We need to refactor the `PriceChart` component.
First we need to use default import for all subcomponents.
We may also need to refactor all sub components to use default export.
> chore(apps/interface): refactor PriceChart

- apps/interface/components/SwapHistoryCard/MySwapContainer.tsx
- apps/interface/components/SwapHistoryCard/index.tsx
- apps/interface/package.json
- pnpm-lock.yaml
Latest main branch have the following error:
```bash
monorepo/apps/interface on 🌱 main [$?] via  v18.7.0 took 1m29s
❯ pnpm build
> interface@0.1.1 build /Users/pyk/github/risedle/monorepo/apps/interface
> next build
info  - Linting and checking validity of types ...Failed to compile.
./components/SwapHistoryCard/index.tsx:124:26
Type error: 'MySwapHistoryContainer' cannot be used as a JSX component.
Its element type 'ReactElement<any, any> | Component<MySwapHisotryContainerProps, any, any> | null' is not a valid JSX element.
Type 'Component<MySwapHisotryContainerProps, any, any>' is not assignable to type 'Element | ElementClass | null'.
Type 'Component<MySwapHisotryContainerProps, any, any>' is not assignable to type 'ElementClass'.
The types …
```
> fix(apps/interface): failed build

- apps/interface/components/SwapCard/SlippageTolerance.tsx
We need to refactor `SwapCardSlippageTolerance` component.
> chore(apps/interface): refactor SwapCardSlippageTolerance

- apps/interface/components/SwapCard/SlippageToleranceRadio.tsx
We need to refactor `SlippageToleranceRadio` component.
> chore(apps/interface): refactor SlippageToleranceRadio

- apps/interface/components/SwapCard/index.tsx
We need to refactor `SwapCard` component.
> chore(apps/interface): refactor SwapCard
