.github/workflows/router-api-prod.yml
.github/workflows/router-api-stag.yml

Use dedicated github environment for `router-api`.
Learn more about github environment [here](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment)

chore(github): Use dedicated env for router-api

---

apps/router-api/README.md

Add information on how to use `/v1` endpoint.
Fix RIS-221

chore(router-api): Update usage information

---

apps/router-api/src/chains.ts
apps/router-api/src/index.ts
apps/router-api/test/dexes.spec.ts

Implement `GET /v1/:chainId/dexs`
It returns list of supported decentralized exchanges.
Fix RIS-219

feat(router-api): Support /v1/:chainId/dexs

---

.github/workflows/risedle-types-release.yml
packages/types/README.md
packages/types/package.json
packages/types/src/chain.ts
packages/types/src/index.ts
packages/types/src/token.ts
packages/types/tsconfig.json

`@risedle/types` is home of all type definitions used across Risedle apps and packages

feat(@risedle/types): setup automatic publish to npm

---

.github/workflows/risedle-types-release.yml
package.json
packages/types/package.json

Enable clean submodule import such as:
```typescript
import { ChainId } from "@risedle/types/chain";
```
Previously:
```typescript
import { ChainId } from "@risedle/types/dist/chain";
```
We use [subpath export](https://stackoverflow.com/a/69104582).

fix(@risedle/types): enable clean submodule import

---

packages/types/src/token.ts

`TokenInfoSource` is enum to represent the data source of given address.
`SourceTokens` is a type that represent raw pair token data:
1. token address
2. where to get the market data of a token
One chain will have one source tokens.

feat(@risedle/types): add TokenInfoSource and SourceTokens

---

packages/types/README.md
packages/types/package.json

Previously we can't do import like this:
```
import { ChainId, Chain } from "@risedle/types";
```
This pull request fix that.

fix(@risedle/types): add index export on package.json

---

package-lock.json
packages/chains/README.md
packages/chains/package.json

Previously we can't do something like this:
```typescript
import { Binance } from "@risedle/chains";
```
this pull request fix that

fix(@risedle/chains): export index

---

.github/workflows/risedle-chains-release.yml

There is this weird build issue https://github.com/risedle/monorepo/runs/6953926041?check_suite_focus=true
`monorepo` workflow build doesn't fail, but this one is. 
Not sure what happen but this pull request is building `@risedle/chains` from the monorepo root instead of package directory

fix(@risedle/chains): run build on root

---

.github/workflows/risedle-types-release.yml
packages/types/package.json

Publish `@risedle/types` on `latest` tag by default

fix(@risedle/types): publish on latest tag by default

---

subgraphs/flt/subgraph.yaml

Error:
```
Subgraph failed with non-deterministic error: failed to process trigger: block #19487278 (0x368f…c69a), transaction 853d3ac75a279b925326dd91252a255f97dbcbb503789713b3ad60219b7b6955: Could not find ABI for contract "FLT", try adding it to the 'abis' section of the subgraph manifest wasm backtrace: 0: 0x3472 - <unknown>!~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.SmartContract#call 1: 0x37dc - <unknown>!src/factory/handleTokenCreated , retry_delay_s: 960, attempt: 3
```

fix(subgraphs/flt): add FLT to abis section in TokenCreated event 

---

apps/rebalancer/Dockerfile

Fix this build https://github.com/risedle/monorepo/runs/7319033348?check_suite_focus=true

fix(apps/rebalancer): disable build inside docker image

---

.github/workflows/risedle-types-release.yml

Use github token when checkout repo in the github action vm

fix(@risedle/types): fix auto-release workflow

---

apps/interface/components/ChainSwitcher/index.tsx

1. Set margin to `0 !important`
2. Hide backdrop blur on tablet or larger screen

chore(apps/interface): set ChainSwitcherPopupBackground margin to 0

---

apps/interface/components/FooterBar/index.tsx
apps/interface/components/TokenCard/cards.tsx

TODO:
Even though the footer bar is hidden on mobile, it still looks like this
The bottom token card content is cut. I'll make a new issue in linear to add margin bottom on the body for mobile layout.

chore(apps/interface): hide FooterBar on mobile

---

apps/interface/components/TradeInfoCard/UserPosition.tsx
apps/interface/components/TradeInfoCard/index.tsx

1. Add dashed border on tablet or larger screen
2. For mobile sceen, we use divider, but for tablet or larger screen, we hide the divider and use border instead. The reason is becase we have `gap='4'` in the `VStack` container, so if we use divider in tablet or larger screen, the border will be separated by those gap.

chore(apps/interface): add dashed border on UserPosition

---

apps/interface/components/TokenCardInfo/index.tsx
apps/interface/components/TradeInfoCard/LatestPrice.tsx
apps/interface/components/TradeInfoCard/UserPosition.tsx
apps/interface/tests/utils/formatPercent.spec.ts
apps/interface/utils/formatPercent.ts

the `priceChangePercent` data from `useFuseLeveragedTokenInfo` already defined in percentage, so we need to divide it with `100` again when using `formatPercentage` (using `Intl`) utils. Wdyt guys? Should we use `Intl` or other way to format percent?

chore(apps/interface): use formatPercent to format percentage

---

apps/interface/components/PriceChart/index.tsx
apps/interface/components/TokenCard/index.tsx
apps/interface/components/TradeInfoCard/index.tsx

Display chart in trade page, even when the screen is smaller than tablet

fix(apps/interface): price chart is hidden on trade page (mobile)

---

apps/interface/components/FooterBar/Sticky.tsx

1. Update horizontal spacing to 24px (for links)
2. Add padding y = 24px
3. Add gap between links & `Risedle Labs` text = 16px
4. Update links order (docs now at the end)
Before:
After:

chore(apps/interface): update StickyFooter space

---

apps/interface/components/Icons/Darkmode.tsx
apps/interface/components/Icons/Lightmode.tsx
apps/interface/tests/components/DarkmodeToggle.spec.tsx

1. Implement test as defined in linear
Note:
https://github.com/risedle/monorepo/blob/2e241907086585022ff3ba1c9cc46590959ed417/apps/interface/tests/components/DarkmodeToggle.spec.tsx#L11-L33
I used `setTimeout()` here because of Chakra UI bug on `useColorMode` hook, where it always return `colorMode = 'light'` on initial render, then changed to `dark` after a few ms.

chore(apps/interface): increase code coverage for DarkmodeToggle

---

apps/ipfs/Dockerfile
apps/ipfs/README.md
apps/ipfs/fly.toml

- Deploy ipfs daemon inside Risedle fly.io private network
- Use [ipfs kubo](https://docs.ipfs.tech/how-to/run-ipfs-inside-docker/#set-up) docker image

feat(apps/ipfs): setup ipfs daemon

---

subgraphs/dex/protocols/uniswap-v3/handlers/handlePoolCreated.ts
subgraphs/dex/tests/uniswap-v3/handlePoolCreated.test.ts

update `pool.createdAtTimestamp` and `pool.createdAtBlockNumber`

fix(subgraphs/dex): set timestamp and blockNumber for pool

---

.github/workflows/monorepo.yml

``` 
- "subgraphs/*"
- ".github/workflows/risedle-subgraphs-*"
```
should be
```
- "subgraphs/**"
- ".github/workflows/risedle-subgraphs-*"
```

fix(monorepo): wrong subgraphs path

---

package.json

Use `--ignore-unknown` instead of writing the file type one by one

chore(monorepo): lint staged graphql files

---

.github/workflows/changesets.yml

n/a
Update the changesets github workflows
Fix RIS-783

chore(monorepo): update changesets ci

---

.github/workflows/changesets.yml

n/a
Add github identity for changeset ci
Fix RIS-786

fix(changesets): set git account identity

---

.github/workflows/changesets.yml
package.json

- packages/*
We need to update the changeset workflow:
1. Enable setupGitUser
2. Remove github identity
3. Add `changeset:release` and `changset:version` command
```json
{
"scripts": {
"changeset:release": "pnpm build && changeset publish",
"changeset:version": "changeset version && pnpm install --lockfile-only",
}
}
```
Fix RIS-787

fix(changesets): update workflow

---

.github/workflows/changesets.yml
package.json

- packages/*
lockfile is not updated.
We need to check `.npmrc` and disable the `--lockfile-only` install. 
Fix RIS-788

fix(changesets): update automatic release

---

.github/workflows/changesets.yml
package.json

- packages/*
Cannot commit due to when running `changeset:version`, the scripts is not ignored.
Fix RIS-789

fix(changesets): automatic release

---

.github/workflows/apps-assets-prod.yml
apps/assets/README.md
apps/assets/package.json

- apps/assets
Deploy command is clashed with builtin `pnpm deploy`.
Update the script name to `pages:deploy`.
Fix RIS-123

fix(apps/assets): deploy script name

---

.github/workflows/apps-api-prod.yml
.github/workflows/apps-api-stag.yml
.github/workflows/packages-chains.yml
.github/workflows/packages-tokens.yml
packages/chains/.npmrc
packages/chains/package.json
packages/tokens/.npmrc
packages/tokens/package.json
pnpm-lock.yaml

- packages/chains
- packages/tokens
- apps/api
Currently the coverage report is overwritten by latest test.
We need to use [Flags](https://docs.codecov.com/docs/flags) to 
solve this problem.
Fix RIS-794

fix(coverage): add flags

---

.github/workflows/changesets.yml
apps/assets/package.json
package.json

- packages/
Currently the automatic release process is not straightforward.
We want to remove the pull request process coz it breaks the build
due to `pnpm changeset version` update other packages that depends on
the updated package(s).
If `package.json` is updated and the dependency is not published yet,
the workflow(s) will fail.
We will use the following step by step to automate the release:
1. Developer run `pnpm changeset` locally
2. Developer commit the changeset and send pull request
3. If pull request is merged to main, it will publish the packages
and push commit and tags.
Fix RIS-795

fix(changesets): simplify workflow

---

.github/workflows/changesets.yml
subgraphs/flt/package.json

- packages/*
Based on the first run of updated [worfklow](https://github.com/risedle/monorepo/runs/8295132573?check_suite_focus=true),
it seems that changesets need to run on whatever updated files.
`changeset status` command is not simply check wether 
there is file in `.changeset` directory or not, it also check the all
defined `package.json` in all workspaces.

fix(changesets): remove paths filter

---

.github/workflows/changesets.yml

- packages/*
`NODE_AUTH_TOKEN` doesn't work with `pnpm packages:publish`.
We need to create `.npmrc` manually.

fix(changesets): set auth via .npmrc

---

.github/workflows/changesets.yml

- changeset
This command `changeset status --since=main` is not returning exit code 1 if there is no changeset found.
We need to check manually via json output.
```sh
✦ cat status.json | jq ".changesets | length" | grep -q 0 && echo "false" || echo "true"
false
✦ cat status_2.json | jq ".changesets | length" | grep -q 0 && echo "false" || echo "true"
true
```

fix(changesets): check changeset via jq

---

apps/interface/Dockerfile

When we try to deploy the `apps/interface` it fails to build the Docker image
with the following error message:
```shell
> [7/8] RUN pnpm install --prod:
#10 25.34  at eth-json-rpc-filters@4.2.2
#10 25.34  at eth-json-rpc-middleware@6.0.0
#10 25.34  at eth-sig-util@1.4.2
#10 25.34 
#10 25.34 pnpm: Command failed with ENOENT: git ls-remote https://github.com/ethereumjs/ethereumjs-abi.git HEAD
#10 25.34 spawn git ENOENT
#10 25.34     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
#10 25.34     at onErrorNT (node:internal/child_process:476:16)
#10 25.34     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
#10 25.34 Progress: resolved 1010, reused 0, downloaded 994, added 0
```
We need to install …

fix(apps/interface): install git on docker image

---

packages/tsconfig/base.json
packages/tsconfig/cjs.json
packages/tsconfig/esm.json

- packages/tsconfig
We need to update the base compiler options to make sure that
we don't include any unnecessary options.
Also we need to introduce `esm.json` and `cjs.json` to target
different output for our published packages.

feat(@risedle/tsconfig): add esm and cjs

---

.changeset/tidy-horses-beam.md
packages/tsconfig/package.json

- packages/tsconfig
Currently `esm.json` and `cjs.json` is not uploaded in the npm module.
We need to add it to `files` config in the `package.json`.

fix(@risedle/tsconfig): include esm and cjs json files

---

apps/interface/components/BackgroundGradient/index.tsx

We need to use default import for all imported utilities in [BackgroundGradient][1].
[1]: https://github.com/risedle/monorepo/blob/92a878c98f5e1ff10cc4420512ad8a626d3083dc/apps/interface/components/BackgroundGradient/index.tsx#L3

chore(apps/interface): refactor BackgroundGradient

---

apps/interface/components/FuseLeveragedTokenInfoCard/index.tsx
apps/interface/components/NavigationBarBottom/index.tsx
apps/interface/pages/index.tsx
apps/interface/pages/trade/[symbol].tsx
apps/interface/utils/fetchFuseLeveragedTokenBySymbol.ts
apps/interface/utils/fetchFuseLeveragedTokenSymbols.ts

We need to use default import for all imported components and utilities in [TradePage][1].
[1]: https://github.com/risedle/monorepo/blob/main/apps/interface/pages/trade/%5Bsymbol%5D.tsx#L5-L18

chore(apps/interface): refactor TradePage imports

---

apps/interface/components/FooterBar/index.tsx
apps/interface/components/HomeHeading/index.tsx
apps/interface/components/TokenCard/cards.tsx
apps/interface/components/WarningBar/index.tsx
apps/interface/pages/index.tsx
apps/interface/pages/shareable.tsx
apps/interface/tests/components/FooterBar.spec.tsx
apps/interface/tests/components/TokenCards.spec.tsx
apps/interface/tests/utils/getFuseLeveragedTokensSummary.spec.ts
apps/interface/utils/fetchFuseLeveragedTokens.ts
apps/interface/utils/getFuseLeveragedTokensSummary.ts

We need to use default import for all imported components and utilities in [IndePage][1].
[1]: https://github.com/risedle/monorepo/blob/main/apps/interface/pages/index.tsx#L4-L15

chore(apps/interface): refactor IndexPage imports

---

apps/interface/components/Icons/ChevronUp.tsx

We need to refactor the `ChevronUpIcon` component.
Return `Icon` directly instead of using `return` keyword.
Update this:
```
const ChevronUpIcon = (props: IconProps) => {
return <Icon />
}
```
to this:
```
const ChevronUpIcon = (props: IconProps) => (
<Icon />
)
```

chore(apps/interface): refactor ChevronUpIcon

---

apps/interface/components/Icons/RedIndicator.tsx

We need to refactor the `RedIndicatorIcon` component.
Return `Icon` directly instead of using `return` keyword.
Update this:
```
const RedIndicatorIcon = (props: IconProps) => {
return <Icon />
}
```
to this:
```
const RedIndicatorIcon = (props: IconProps) => (
<Icon />
)
```

chore(apps/interface): refactor RedIndicatorIcon

---

apps/interface/components/BackingCard/AllocationTable.tsx

Currently the BackingCard [AllocationTable][1] is implemented as multiple VStack
stacked together.
We need to use Chakra `Table` component instead of using the div.
[1]: https://github.com/risedle/monorepo/blob/main/apps/interface/components/BackingCard/AllocationTable.tsx#L65

chore(apps/interface): refactor BackingCard AllocationTable

---

apps/interface/components/Icons/ChevronDown.tsx

We need to refactor the `ChevronDownIcon` component.
Return `Icon` directly instead of using `return` keyword.
Update this:
```
const ChevronDownIcon = (props: IconProps) => {
return <Icon />
}
```
to this:
```
const ChevronDownIcon = (props: IconProps) => (
<Icon />
)
```

chore(apps/interface): refactor ChevronDownIcon

---

.github/workflows/apps-interface-prod.yml
.github/workflows/apps-interface-stats.yml

We want to be able to merge apps/interface change to main branch without
waiting the deployment finished.
In order to do that, we need to add concurrency in the `apps-interface-stag.yml`
and `apps-interface-prod.yml` github workflow.
```yaml
concurrency: interface
```

chore(apps/interface): add concurrency flag to workflow

---

apps/interface/README.md
apps/interface/app/layout.tsx
apps/interface/controller/home.ts
apps/interface/controller/index.ts
apps/interface/entrypoint.server.ts
apps/interface/env.ts
apps/interface/package.json
apps/interface/router/index.ts
apps/interface/tsconfig.exchange.json
apps/interface/tsconfig.json
apps/interface/wrangler.toml
pnpm-lock.yaml

Initialize edge-rendered React apps.
Edge-rendered React apps is a React app that rendered on the Cloudflare Workers.
To prepare our new Risedle Exchange, we need to build the following react apps:
- Just-in-time rendering on the edge.
- Partial based client hydration for maximum interactivity.
- Zero runtime overhead. no JS is shipped to the client by default.
We need to initialize the project. We need to add the following scripts:
```bash
pnpm exchange:dev
pnpm exchange:type
pnpm exchange:deploy
```

feat(apps/interface): initialize Edge-rendered React app

---

.github/workflows/apps-rebalancer-stag.yml

There is invalid path in the `apps-rebalancer-stag.yml` https://github.com/risedle/monorepo/blob/d658b97f2d9b483038e9b5abe7bf1a5c5a834684/.github/workflows/apps-rebalancer-stag.yml#L10
This should be `/apps-rebalancer-stag.yml` instead of `/apps-rebalancer.yml`

fix(apps/interface): rebalancer staging worklow

---

apps/interface/components/NavigationBarBottom/index.tsx
apps/interface/components/NavigationBarBottom/links.tsx
apps/interface/tests/components/NavigationBarBottomLinks.spec.tsx

We need to refactor the `NavigationBarBottom` component.
First we need to use default import for all subcomponents:
```typescript
// this
import { NavigationBarBottomLinks } from "./links";
// to this
import NavigationBarBottomLinks from "./links";
```
We may also need to refactor all sub components to use default export.

chore(apps/interface): refactor NavigationBarBottom

---

apps/interface/tests/components/SwapCard/SellCTACointainer.spec.tsx

We need to increase the test coverage for the `SellCTAContainer` component.
First we need to create new file:
```
tests/components/SwapCard/SellCTAContainer.spec.tsx
```
Here is the test case that we need to add to the test:
1. Given `amount = ""`, button `data-testid="CTAEnterAmountButton"` should be rendered.
2. Given `data == null || (data && data[0] == null)`, button `data-testid="CTALoadingButton"` should be rendered.
3. Given `amountIn.gt(userBalance)`, button `data-testid="CTANotEnoughBalanceButton"` should be rendered.
6. Given `waitApproval.isLoading`, button `data-testid="CTAApprovingButton"` should be rendered
7. Given `amountIn.gte(allowanceAmount)`, button `data-testid="CTAApprovalButton"` should be rendered
8. Given …

chore(apps/interface): increase coverage for SellCTAContainer
